#
# Copyright 2009 Joe Block <jpb@ApesSeekingKnowledge.net>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Install settings to disable Logic registration nags, both at the system
# level and in the User Template ByHost area (generating the hardware
# UUID based on the system performing the install)

include /usr/local/share/luggage/luggage.make

TITLE=LogicStudio3-DisableRegistration
REVERSE_DOMAIN=com.example.corp
PACKAGE_VERSION=20110413
PAYLOAD=pack-script-postflight